[package]
name = "pigment64"
version = "0.4.4"
edition = "2021"
description = "A library for handling conversion between N64 texture formats and modern image formats"
repository = "https://github.com/decompals/pigment64"
license = "MIT"

[dependencies]
png = "0.17.13"
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.81"
byteorder = "1.5.0"
num_enum = "0.7.2"
strum = "0.26.2"
strum_macros = "0.26.2"
