[package]
name = "pigment64"
version = "0.4.1"
edition = "2021"
description = "A library for handling conversion between N64 texture formats and modern image formats"
repository = "https://github.com/decompals/pigment64"
license = "MIT"

[dependencies]
png = "0.17.10"
clap = { version = "4.4.13", features = ["derive"] }
anyhow = "1.0.79"
byteorder = "1.5.0"
num_enum = "0.7.1"
