name: Python bindings

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
    tests_cases:
        name: Tests for Python ${{ matrix.py_version}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11", "3.12", "3.13, 3.14"]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Setup Python ${{ matrix.py_version }}
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.py_version }}

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install maturin pytest
            - name: Build and install
              run: maturin develop
            - name: Test
              run: python3 -m pytest
