name: Build and upload Rust crate

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"
  CI: "true"

jobs:
  check_fmt:
    name: Check format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup rustfmt
        run: rustup component add rustfmt

      - name: Check format
        run: cargo fmt --all --check

  check_clippy:
    name: Check clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup clippy
        run: rustup component add clippy

      - name: Run clippy
        run: |
          cargo clippy --version
          cargo clippy --all --all-targets

  check_doc:
    name: Check doc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run doc tets
        run: cargo test --doc

      - name: Run doc
        run: cargo doc

  run_tests:
    name: Run tests (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: macos-latest
          - runner: windows-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test

  check_msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup MSRV checker
        uses: taiki-e/install-action@cargo-hack

      - name: Run MSRV checker
        run: cargo hack check --rust-version --workspace --all-targets --ignore-private

  check_semver:
    name: Check semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      # Locally:
      # ```
      # cargo install cargo-semver-checks --locked
      # cargo semver-checks
      # ```
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          feature-group: default-features

  publish_pigment64:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs:
      - check_fmt
      - check_clippy
      - check_doc
      - run_tests
      - check_msrv
      - check_semver

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rust package
        run: cargo build --locked --release

      - name: Publish pigment64 (dry run)
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        run: cargo publish --dry-run

      - name: Publish pigment64 crate
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: cargo publish --token ${{ secrets.CRATE_AUTH_TOKEN }}

  github_binary_release:
    name: ${{ matrix.binaries.package }} (${{ matrix.builder.target }}) binary release
    runs-on: ${{ matrix.builder.runner }}
    needs:
      - check_fmt
      - check_clippy
      - check_doc
      - run_tests
      - check_msrv
      - check_semver

    strategy:
      fail-fast: false
      matrix:
        builder: [
          {
            name: linux,
            target: x86_64-unknown-linux-musl,
            runner: ubuntu-22.04,
            cp_cmd: cp,
            extension: "",
          },
          {
            name: linux,
            target: x86_64-unknown-linux-gnu,
            runner: ubuntu-22.04,
            cp_cmd: cp,
            extension: "",
          },
          {
            name: mac,
            target: x86_64-apple-darwin,
            runner: macos-15-intel,
            cp_cmd: cp,
            extension: "",
          },
          {
            name: mac,
            target: aarch64-apple-darwin,
            runner: macos-14,
            cp_cmd: cp,
            extension: "",
          },
          {
            name: windows,
            target: x86_64-pc-windows-gnu,
            runner: windows-2022,
            cp_cmd: Copy-Item,
            extension: ".exe",
          },
          {
            name: windows,
            target: x86_64-pc-windows-msvc,
            runner: windows-2022,
            cp_cmd: Copy-Item,
            extension: ".exe",
          },
          {
            name: windows,
            target: aarch64-pc-windows-msvc,
            runner: windows-2022,
            cp_cmd: Copy-Item,
            extension: ".exe",
          },
        ]
        binaries: [
          {
            package: pigment64,
          },
        ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.builder.target }}

      - name: Build ${{ matrix.binaries.package }}
        run: |
          cargo build --release --locked --target ${{ matrix.builder.target }}

      - name: Move files for packaging
        run: |
          mkdir -p package/
          ${{ matrix.builder.cp_cmd }} target/${{ matrix.builder.target }}/release/${{ matrix.binaries.package }}${{ matrix.builder.extension }} package/
          ${{ matrix.builder.cp_cmd }} README.md package/${{ matrix.binaries.package }}.README.md
          ${{ matrix.builder.cp_cmd }} LICENSE package/${{ matrix.binaries.package }}.LICENSE

      - name: Package .tar.gz
        run: |
          cd package/ && tar -czf ../${{ matrix.binaries.package }}-${{ matrix.builder.target }}.tar.gz *

      - name: Upload .tar.gz artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.binaries.package }}-${{ matrix.builder.target }}
          path: |
            ${{ matrix.binaries.package }}-${{ matrix.builder.target }}.tar.gz
          if-no-files-found: error

      - name: Publish .tar.gz release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.binaries.package }}-${{ matrix.builder.target }}.tar.gz
